apiVersion: v1
kind: Service
metadata:
  name: node-port
  labels:
    run: node-port
spec:
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    name: http
  type: NodePort
  selector:
    app: nginx
